FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
COPY src ./src
COPY config ./config
COPY lombok.config ./
RUN chmod 774 ./mvnw && ./mvnw clean install -DskipTests
# Download and Install Jmeter
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*
RUN curl -L -o /tmp/apache-jmeter.zip https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.5.zip \
    && unzip /tmp/apache-jmeter.zip -d /opt/ \
    && rm /tmp/apache-jmeter.zip \
    && ln -s /opt/apache-jmeter-5.5/bin/jmeter /usr/local/bin/jmeter   
CMD ["./mvnw", "spring-boot:run"]
