spring.application.name=garang-guni-backend
spring.profiles.active=dev
server.port=${PORT:8080}

#JWT CONFIG
security.jwt.private-key=classpath:certs/private.pem
security.jwt.public-key=classpath:certs/public.pem
security.jwt.ttl=15

#SPRING MAIL CONFIG
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.mail.host=mailhog
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
email.verification-required=false