name: Java CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      SPRING_DATASOURCE_DB: ${{ secrets.SPRING_DATASOURCE_DB }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      CONNECTION_TO_DATABASE_HOST_PORT: ${{ secrets.CONNECTION_TO_DATABASE_HOST_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run Docker Compose
        run: docker compose up -d --build

      - name: Run SpotBugs
        run: docker exec spring_boot_app ./mvnw spotbugs:check

      - name: Run unit tests and system tests
        run: docker exec spring_boot_app ./mvnw test

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        continue-on-error: true
        with:
          args: |
            test
            --file=pom.xml
            --sarif-file-output=snyk.sarif
            --json=true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      
      - name: Check for Critical vulnerabilities
        run: |
          if [ -f snyk.json ]; then
            if grep -q "Critical" snyk.json; then
              echo "Critical vulnerabilities found!"
              exit 1
            else
              echo "No critical vulnerabilities found."
            fi
          else
            echo "No Snyk report generated."
            exit 1
          fi
